# Generated by Django 5.2.16 on 2026-07-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(
                        help_text="The situation text shown to the user, e.g. 'Your car won't start and the mechanic says it needs a new transmission.'"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position in the simulation sequence (1 = first scenario)."
                    ),
                ),
                (
                    "location_tag",
                    models.CharField(
                        help_text="Which 3D scene/location this happens at, e.g. 'mechanic_shop', 'bank', 'apartment'. The Three.js frontend uses this to know which environment to load.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Identifies which browser session this run belongs to, since we don't have logins yet.",
                        max_length=40,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "starting_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "starting_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_monthly_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short text shown on the choice button.",
                        max_length=120,
                    ),
                ),
                (
                    "immediate_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="One-time cost of this choice (enter as a positive number).",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ongoing monthly cost (positive) or savings (negative) from this choice.",
                        max_digits=10,
                    ),
                ),
                (
                    "debt_added",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Any new debt this choice creates (e.g. taking a loan).",
                        max_digits=10,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Short explanation shown after picking this, e.g. why it was a smart or risky move.",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="simulator.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.choice",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.scenario",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="simulator.simulationrun",
                    ),
                ),
            ],
        ),
    ]
