# Generated by Django 5.2.16 on 2026-07-30 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "down_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("rate", models.FloatField(default=0)),
                ("term_months", models.IntegerField(default=60)),
                (
                    "income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commitments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("verdict", models.CharField(blank=True, max_length=32)),
                (
                    "payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
